actions:
  actionDefs:
    create:
      roles: 
      - etcdAdmin

      # Requires the prerequisite Kubernetes version, amd64 Linux operating system, and the etcdRestore CRD to be installed
      requires:
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - "/case/prereqs/k8sResources/workerIntelLinux"
        - "/case/prereqs/k8sResourceVersions/etcdRestore"

      k8sPermissions:
        rules:
        - rule: 
            group: etcd.database.coreos.com
            resource: EtcdRestore
            verbs:
            - 'get'
            - 'list'
            - 'create'
    remove:
      roles: 
      - etcdAdmin

      requires:
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - "/case/prereqs/k8sResources/workerIntelLinux"
        - "/case/prereqs/k8sResourceVersions/etcdRestore"

      k8sPermissions:
        rules:
        - rule: 
            group: etcd.database.coreos.com
            resource: EtcdRestore
            verbs:
            - '*'