apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-binding
  namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-restricted-psp-etcd-cr
subjects:
- kind: ServiceAccount
  name: etcdServiceAccount
  namespace: <namespace-name>